* Encoding: UTF-8.
UNIANOVA 값 BY grpA grpB
  /METHOD=SSTYPE(1)
  /INTERCEPT=INCLUDE
  /CRITERIA=ALPHA(0.05)
  /DESIGN=grpA grpB grpA*grpB.

UNIANOVA 값 BY grpB grpA
  /METHOD=SSTYPE(1)
  /INTERCEPT=INCLUDE
  /CRITERIA=ALPHA(0.05)
  /DESIGN=grpB grpA grpB*grpA.

UNIANOVA 값 BY grpB grpA
  /METHOD=SSTYPE(2)
  /INTERCEPT=INCLUDE
  /CRITERIA=ALPHA(0.05)
  /DESIGN=grpB grpA grpB*grpA.

UNIANOVA 값 BY grpB grpA
  /METHOD=SSTYPE(3)
  /INTERCEPT=INCLUDE
  /CRITERIA=ALPHA(0.05)
  /DESIGN=grpB grpA grpB*grpA.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpA1 grpA2.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpB1 grpB2.

REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpA1 grpA2 grpB1 grpB2.

  REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpA1 grpA2 grpA1B1 grpA1B2 grpA2B1 grpA2B2.

  REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpB1 grpB2 grpA1B1 grpA1B2 grpA2B1 grpA2B2.

  REGRESSION
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA
  /CRITERIA=PIN(.05) POUT(.10)
  /NOORIGIN
  /DEPENDENT 값
  /METHOD=ENTER grpA1 grpA2 grpB1 grpB2 grpA1B1 grpA1B2 grpA2B1 grpA2B2.


